package ntemoji

// Emoji constants for standard, widely supported TUI-friendly emojis.
// Using constants helps developers reference emojis programmatically by name.
//
// NOTE: To ensure pixel-perfect TUI borders and layout alignment, all emojis
// defined here are strictly curated to have a visual width of 2 columns. Emojis
// containing variation selectors (like \ufe0f, e.g., ⚠️ or 🌧️) are avoided because
// they cause rendering conflicts: standard libraries (Lip Gloss / uniseg) report
// them as 2 columns, but terminal emulators render them as 1 column.
const (
	// === Smileys & Emotion ===
	EmojiGrinningFace       = "😀"
	EmojiGrinningWithEyes   = "😃"
	EmojiSmilingWithOpen    = "😄"
	EmojiGrinningSquinting  = "😆"
	EmojiSmilingSweat       = "😅"
	EmojiTearsOfJoy         = "😂"
	EmojiRollingOnFloor     = "🤣"
	EmojiSmilingFace        = "😊"
	EmojiAngelFace          = "😇"
	EmojiSlightlySmiling    = "🙂"
	EmojiUpsideDown         = "🙃"
	EmojiWinkingFace        = "😉"
	EmojiRelievedFace       = "😌"
	EmojiHeartEyes          = "😍"
	EmojiSmilingWithHearts  = "🥰"
	EmojiKissingFace        = "😘"
	EmojiThinkingFace       = "🤔"
	EmojiShushingFace       = "🤫"
	EmojiGrimacingFace      = "😬"
	EmojiZippedMouth        = "🤐"
	EmojiSweatFace          = "😓"
	EmojiCryingFace         = "😢"
	EmojiLoudlyCrying       = "😭"
	EmojiAngryFace          = "😠"
	EmojiRedAngryFace       = "😡"
	EmojiExplodingHead      = "🤯"
	EmojiHotFace            = "🥵"
	EmojiColdFace           = "🥶"
	EmojiSleepingFace       = "😴"
	EmojiNerdFace           = "🤓"
	EmojiCoolFace           = "😎"
	EmojiPartyFace          = "🥳"

	// === Hands & Gestures ===
	EmojiWave               = "👋"
	EmojiRaisedHand         = "✋"
	EmojiVulcanSalute       = "🖖"
	EmojiOkHand             = "👌"
	EmojiCrossedFingers     = "🤞"
	EmojiThumbsUp           = "👍"
	EmojiThumbsDown         = "👎"
	EmojiClappingHands      = "👏"
	EmojiRaisedHands        = "🙌"
	EmojiFoldedHands        = "🙏"
	EmojiFlexedBiceps       = "💪"

	// === Animals & Nature ===
	EmojiCatFace            = "🐱"
	EmojiCat                = "🐈"
	EmojiDogFace            = "🐶"
	EmojiDog                = "🐕"
	EmojiFox                = "🦊"
	EmojiLion               = "🦁"
	EmojiTigerFace          = "🐯"
	EmojiMonkeyFace         = "🐵"
	EmojiCowFace            = "🐮"
	EmojiPigFace            = "🐷"
	EmojiFrog               = "🐸"
	EmojiOctopus            = "🐙"
	EmojiBee                = "🐝"
	EmojiBug                = "🐛"
	EmojiPenguin            = "🐧"
	EmojiOwl                = "🦉"
	EmojiTurtle             = "🐢"
	EmojiSnake              = "🐍"
	EmojiDolphin            = "🐬"
	EmojiTree               = "🌲"
	EmojiEvergreen          = "🌲"
	EmojiDeciduousTree      = "🌳"
	EmojiCactus             = "🌵"
	EmojiMapleLeaf          = "🍁"
	EmojiSun                = "🌞"
	EmojiRainbow            = "🌈"
	EmojiSnowman            = "⛄"
	EmojiLightning          = "⚡"
	EmojiFire               = "🔥"
	EmojiWaterWave          = "🌊"
	EmojiGlobe              = "🌍"

	// === Food & Drink ===
	EmojiGreenApple         = "🍏"
	EmojiRedApple           = "🍎"
	EmojiBanana             = "🍌"
	EmojiWatermelon         = "🍉"
	EmojiGrapes             = "🍇"
	EmojiStrawberry         = "🍓"
	EmojiPizza              = "🍕"
	EmojiHamburger          = "🍔"
	EmojiFrenchFries        = "🍟"
	EmojiHotDog             = "🌭"
	EmojiTaco               = "🌮"
	EmojiPopcorn            = "🍿"
	EmojiRiceBall           = "🍙"
	EmojiSushi              = "🍣"
	EmojiIceCream           = "🍦"
	EmojiDoughnut           = "🍩"
	EmojiCookie             = "🍪"
	EmojiBirthdayCake       = "🎂"
	EmojiCoffee             = "☕"
	EmojiTea                = "🍵"
	EmojiBeerMug            = "🍺"
	EmojiWineGlass          = "🍷"
	EmojiCocktail           = "🍸"

	// === Status, UI & Shapes ===
	EmojiCheckMarkButton    = "✅"
	EmojiCrossMark          = "❌"
	EmojiWarning            = "🚨"
	EmojiInfo               = "📢"
	EmojiRedCircle          = "🔴"
	EmojiYellowCircle       = "🟡"
	EmojiGreenCircle        = "🟢"
	EmojiBlueCircle         = "🔵"
	EmojiPurpleCircle       = "🟣"
	EmojiBlackSquare        = "⬛"
	EmojiWhiteSquare        = "⬜"
	EmojiStopSign           = "🛑"
	EmojiConstruction       = "🚧"
	EmojiChequeredFlag      = "🏁"
	EmojiTriangularFlag     = "🚩"
	EmojiBell               = "🔔"
	EmojiMutedBell          = "🔕"
	EmojiMegaphone          = "📣"
	EmojiHourglass          = "⏳"
	EmojiHourglassEmpty     = "⌛"
	EmojiSpeechBalloon      = "💬"
	EmojiHeart              = "💖"
	EmojiBrokenHeart        = "💔"
	EmojiSparkles           = "✨"
	EmojiCollision          = "💥"
	EmojiRocket             = "🚀"

	// === Objects & Tools ===
	EmojiComputer           = "💻"
	EmojiDesktop            = "🖥️"
	EmojiFloppyDisk         = "💾"
	EmojiCamera             = "📷"
	EmojiFolder             = "📁"
	EmojiOpenFolder         = "📂"
	EmojiCalendar           = "📅"
	EmojiBarChart           = "📊"
	EmojiChartUp            = "📈"
	EmojiChartDown          = "📉"
	EmojiMemo               = "📝"
	EmojiEnvelope           = "📩"
	EmojiIncomingMail       = "📨"
	EmojiPackage            = "📦"
	EmojiGear               = "🔧"
	EmojiWrench             = "🔧"
	EmojiHammer             = "🔨"
	EmojiToolbox            = "🧰"
	EmojiKey                = "🔑"
	EmojiLock               = "🔒"
	EmojiUnlock             = "🔓"
	EmojiPaperclip          = "📎"
	EmojiLightBulb          = "💡"
	EmojiMagnifyingGlass    = "🔍"

	// === Navigation ===
	EmojiArrowUp            = "🔼"
	EmojiArrowDown          = "🔽"
	EmojiArrowLeft          = "👈"
	EmojiArrowRight         = "👉"
	EmojiRefresh            = "🔄"
)
